# Generated by Django 5.1.4 on 2024-12-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='tmdb_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
